/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package startup;

/**
 *
 * @author DELL
 */
public class Bio_FirstSemester extends javax.swing.JPanel {

    /**
     * Creates new form Bio_FirstSemester
     */
    private double GPA;
    public Bio_FirstSemester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();
        cmb_GCB = new javax.swing.JComboBox<>();
        cmb_GCBP = new javax.swing.JComboBox<>();
        cmb_PR = new javax.swing.JComboBox<>();
        cmb_PS = new javax.swing.JComboBox<>();
        cmb_GPC = new javax.swing.JComboBox<>();
        cmb_CC = new javax.swing.JComboBox<>();
        cmb_PC = new javax.swing.JComboBox<>();
        cmb_EB = new javax.swing.JComboBox<>();
        cmb_ES = new javax.swing.JComboBox<>();
        cmb_AM = new javax.swing.JComboBox<>();
        cmb_CS = new javax.swing.JComboBox<>();
        chk_plant = new javax.swing.JCheckBox();
        chk_chem = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        lbl_gpa = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(678, 739));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Genetics and Cell Biology");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 78, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 43, 552, 20));

        jLabel2.setText("Botany");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, -1, -1));

        jLabel3.setText("Genetics and Cell Biology Practicals");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 117, -1, -1));

        jLabel4.setText("Plant Resources");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 159, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 233, 529, 20));

        jLabel6.setText("Chemistry");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 233, -1, -1));

        jLabel7.setText("General and Physical Chemistry");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 275, -1, -1));

        jLabel9.setText("Practical Chemistry I");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 359, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 395, 543, 20));

        jLabel10.setText("Zoology");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 395, -1, -1));

        jLabel11.setText("Evolution and Biogeography");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 430, -1, -1));

        jLabel12.setText("Introduction to Environmental Sciences");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 472, -1, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 501, 454, 20));

        jLabel13.setText("Applied Mathematics");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 501, -1, -1));

        jLabel14.setText("Mathematics for Biological Science Students");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 543, -1, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 579, 473, 20));

        jLabel15.setText("Computer Science");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 579, -1, -1));

        jLabel16.setText("Introduction to Computing");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 621, -1, -1));

        btn_calculate.setText("Calculate");
        btn_calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_calculateMouseClicked(evt);
            }
        });
        add(btn_calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, -1, -1));

        cmb_GCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_GCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 72, 84, -1));

        cmb_GCBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_GCBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 114, 84, -1));

        cmb_PR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_PR, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 156, 84, -1));

        cmb_PS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_PS, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 198, 84, -1));

        cmb_GPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_GPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 269, 84, -1));

        cmb_CC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 311, 84, -1));

        cmb_PC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 353, 84, -1));

        cmb_EB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_EB, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 424, 84, -1));

        cmb_ES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_ES, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 466, 84, -1));

        cmb_AM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_AM, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 537, 84, -1));

        cmb_CS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        add(cmb_CS, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 615, 84, -1));

        chk_plant.setText("Plant Structure");
        add(chk_plant, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 195, -1, -1));

        chk_chem.setText("Calculations in Chemistry");
        chk_chem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_chemActionPerformed(evt);
            }
        });
        add(chk_chem, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 308, -1, -1));

        jLabel5.setText("Your GPA is:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 110, -1));
        add(lbl_gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculateMouseClicked
            Bio_FirstSemesterGPA b = new Bio_FirstSemesterGPA((cmb_GCB.getSelectedItem()).toString(),(cmb_GCBP.getSelectedItem()).toString(),(cmb_PR.getSelectedItem()).toString(),(cmb_PS.getSelectedItem()).toString(),(cmb_GPC.getSelectedItem()).toString(),(cmb_CC.getSelectedItem()).toString(),(cmb_PC.getSelectedItem()).toString(),(cmb_EB.getSelectedItem()).toString(),(cmb_ES.getSelectedItem()).toString(),(cmb_AM.getSelectedItem()).toString(),(cmb_CS.getSelectedItem()).toString());
            GPA = b.calculateFFGPA((cmb_GCB.getSelectedItem()).toString(),(cmb_GCBP.getSelectedItem()).toString(),(cmb_PR.getSelectedItem()).toString(),(cmb_PS.getSelectedItem()).toString(),(cmb_GPC.getSelectedItem()).toString(),(cmb_CC.getSelectedItem()).toString(),(cmb_PC.getSelectedItem()).toString(),(cmb_EB.getSelectedItem()).toString(),(cmb_ES.getSelectedItem()).toString(),(cmb_AM.getSelectedItem()).toString(),(cmb_CS.getSelectedItem()).toString());
            lbl_gpa.setText(Double.toString(GPA));
// TODO add your handling code here:
    }//GEN-LAST:event_btn_calculateMouseClicked

    private void chk_chemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_chemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_chemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JCheckBox chk_chem;
    private javax.swing.JCheckBox chk_plant;
    private javax.swing.JComboBox<String> cmb_AM;
    private javax.swing.JComboBox<String> cmb_CC;
    private javax.swing.JComboBox<String> cmb_CS;
    private javax.swing.JComboBox<String> cmb_EB;
    private javax.swing.JComboBox<String> cmb_ES;
    private javax.swing.JComboBox<String> cmb_GCB;
    private javax.swing.JComboBox<String> cmb_GCBP;
    private javax.swing.JComboBox<String> cmb_GPC;
    private javax.swing.JComboBox<String> cmb_PC;
    private javax.swing.JComboBox<String> cmb_PR;
    private javax.swing.JComboBox<String> cmb_PS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_gpa;
    // End of variables declaration//GEN-END:variables
}
