/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package startup;
  
import java.awt.*; 
  

/**
 *
 * @author DELL
 */
public class Years extends javax.swing.JFrame {
private double GPA;
    /**
     * Creates new form Years
     */
    public Years() {
        
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jButton5 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_calculate = new javax.swing.JButton();
        cmb_GCB = new javax.swing.JComboBox<>();
        cmb_GCBP = new javax.swing.JComboBox<>();
        cmb_PR = new javax.swing.JComboBox<>();
        cmb_PS = new javax.swing.JComboBox<>();
        cmb_GPC = new javax.swing.JComboBox<>();
        cmb_CC = new javax.swing.JComboBox<>();
        cmb_PC = new javax.swing.JComboBox<>();
        cmb_EB = new javax.swing.JComboBox<>();
        cmb_ES = new javax.swing.JComboBox<>();
        cmb_AM = new javax.swing.JComboBox<>();
        cmb_CS = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbl_gpa = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btn_calculate1 = new javax.swing.JButton();
        cmb_PML = new javax.swing.JComboBox<>();
        cmb_PMLP = new javax.swing.JComboBox<>();
        cmb_FS = new javax.swing.JComboBox<>();
        cmb_OC = new javax.swing.JComboBox<>();
        cmb_ICS = new javax.swing.JComboBox<>();
        cmb_PCA = new javax.swing.JComboBox<>();
        cmb_AL = new javax.swing.JComboBox<>();
        cmb_AB = new javax.swing.JComboBox<>();
        cmb_FP = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        lbl_gpa1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btn_calculate2 = new javax.swing.JButton();
        cmb_MB = new javax.swing.JComboBox<>();
        cmb_MBRD = new javax.swing.JComboBox<>();
        cmb_MMP = new javax.swing.JComboBox<>();
        cmb_IPC = new javax.swing.JComboBox<>();
        cmb_PCII = new javax.swing.JComboBox<>();
        cmb_AF = new javax.swing.JComboBox<>();
        cmb_EM = new javax.swing.JComboBox<>();
        cmb_IT = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        lbl_gpa2 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        cmb_BS = new javax.swing.JComboBox<>();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        cmb_NS = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        btn_calculate3 = new javax.swing.JButton();
        cmb_PBP = new javax.swing.JComboBox<>();
        cmb_PBPP = new javax.swing.JComboBox<>();
        cmb_IAC = new javax.swing.JComboBox<>();
        cmb_IB = new javax.swing.JComboBox<>();
        cmb_PE = new javax.swing.JComboBox<>();
        cmb_BS1 = new javax.swing.JComboBox<>();
        cmb_SE = new javax.swing.JComboBox<>();
        jLabel59 = new javax.swing.JLabel();
        lbl_gpa3 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        cmb_PD = new javax.swing.JComboBox<>();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        cmb_NT = new javax.swing.JComboBox<>();
        cmb_GSO = new javax.swing.JComboBox<>();
        jLabel61 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(644, 559));
        setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Back to Main");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 800, -1, -1));

        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setPreferredSize(new java.awt.Dimension(692, 750));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, "Welcome");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Genetics and Cell Biology");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 43, 552, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Botany");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, -1, -1));

        jLabel3.setText("Genetics and Cell Biology Practicals");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Plant Resources");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 233, 529, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Chemistry");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 233, -1, -1));

        jLabel7.setText("General and Physical Chemistry");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel9.setText("Practical Chemistry I");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 395, 543, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Zoology");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 395, -1, -1));

        jLabel11.setText("Evolution and Biogeography");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel12.setText("Introduction to Environmental Sciences");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 501, 454, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Applied Mathematics");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 501, -1, -1));

        jLabel14.setText("Mathematics for Biological Science Students");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 579, 473, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Computer Science");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 579, -1, -1));

        jLabel16.setText("Introduction to Computing");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        btn_calculate.setText("Calculate");
        btn_calculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_calculateMouseClicked(evt);
            }
        });
        jPanel2.add(btn_calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, -1, -1));

        cmb_GCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_GCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 72, 84, -1));

        cmb_GCBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_GCBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 114, 84, -1));

        cmb_PR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_PR, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 156, 84, -1));

        cmb_PS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_PS, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 198, 84, -1));

        cmb_GPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_GPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 269, 84, -1));

        cmb_CC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 311, 84, -1));

        cmb_PC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 353, 84, -1));

        cmb_EB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_EB, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 424, 84, -1));

        cmb_ES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_ES, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 466, 84, -1));

        cmb_AM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_AM, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 537, 84, -1));

        cmb_CS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel2.add(cmb_CS, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 615, 84, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Your GPA is:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 110, -1));

        lbl_gpa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(lbl_gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 110, 30));

        jLabel8.setText("Calculations in Chemistry");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel17.setText("Plant Structure");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        mainPanel.add(jPanel2, "FyFs");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Variety of Plant and Microbial Life");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 43, 552, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Botany");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, -1, -1));

        jLabel20.setText("Variety of Plant and Microbial Life Practicals");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel21.setText("Flora of Sri Lanka");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 233, 529, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Chemistry");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 233, -1, -1));

        jLabel23.setText("Organic Chemistry");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel24.setText("Practical Chemistry I");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 395, 543, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Zoology");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 395, -1, -1));

        jLabel26.setText("Variety of Animal Life");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel27.setText("Animal Behaviour");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 579, 473, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Computer Science");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 579, -1, -1));

        jLabel31.setText("Fundamentals of Programming");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        btn_calculate1.setText("Calculate");
        btn_calculate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_calculate1MouseClicked(evt);
            }
        });
        jPanel3.add(btn_calculate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, -1, -1));

        cmb_PML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_PML, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 72, 84, -1));

        cmb_PMLP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_PMLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 114, 84, -1));

        cmb_FS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_FS, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 156, 84, -1));

        cmb_OC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_OC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 269, 84, -1));

        cmb_ICS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_ICS, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 311, 84, -1));

        cmb_PCA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_PCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 353, 84, -1));

        cmb_AL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_AL, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 424, 84, -1));

        cmb_AB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_AB, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 466, 84, -1));

        cmb_FP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel3.add(cmb_FP, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 615, 84, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 0, 51));
        jLabel32.setText("Your GPA is:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 110, -1));

        lbl_gpa1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(lbl_gpa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 110, 30));

        jLabel33.setText("Impact of Chemistry on Society");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        mainPanel.add(jPanel3, "FySs");

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Principles of Microbiology");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 43, 552, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Botany");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, -1, -1));

        jLabel34.setText("Introductory Molecular Biology and Recombinant DNA technology");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel35.setText("Biostatistics");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 233, 529, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Chemistry");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 233, -1, -1));

        jLabel37.setText("Intermediate Physical Chemistry");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 543, 20));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("Zoology");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel40.setText("Animal Form and Function");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel41.setText("Fundamentals of Environmental Management");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        jPanel4.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 579, 473, 20));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setText("Computer Science");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 579, -1, -1));

        jLabel43.setText("Internet Technologies");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        btn_calculate2.setText("Calculate");
        btn_calculate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_calculate2MouseClicked(evt);
            }
        });
        jPanel4.add(btn_calculate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, -1, -1));

        cmb_MB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_MB, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 72, 84, -1));

        cmb_MBRD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_MBRD, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 114, 84, -1));

        cmb_MMP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_MMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 80, -1));

        cmb_IPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_IPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 269, 84, -1));

        cmb_PCII.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_PCII, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 311, 84, -1));

        cmb_AF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 84, -1));

        cmb_EM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_EM, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 84, -1));

        cmb_IT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_IT, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 615, 84, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 0, 51));
        jLabel44.setText("Your GPA is:");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 110, -1));

        lbl_gpa2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(lbl_gpa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 110, 30));

        jLabel45.setText("Practical Chemistry Level II");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel46.setText("Microbiology and Molecular Biology Practicals");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        cmb_BS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_BS, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 156, 84, -1));
        jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 543, 20));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47.setText("Nuclear Science");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel48.setText("Introduction to Nuclear Science");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        cmb_NS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel4.add(cmb_NS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 84, -1));

        mainPanel.add(jPanel4, "SyFs");

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setText("Plant Biochemistry and Physiology");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel5.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 43, 552, 20));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel49.setText("Botany");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 43, -1, -1));

        jLabel50.setText("Plant Biochemistry and Physiology Practicals");
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel51.setText("Plant Development");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel5.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 529, 20));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setText("Chemistry");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel53.setText("Inorganic and Analytical Chemistry");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel5.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 543, 20));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel54.setText("Zoology");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel55.setText("Principles of Ecology");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel56.setText("Biosystematics");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        jPanel5.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 579, 473, 20));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel57.setText("Computer Science");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 579, -1, -1));

        jLabel58.setText("Fundamentals of Software Engineering");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        btn_calculate3.setText("Calculate");
        btn_calculate3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_calculate3MouseClicked(evt);
            }
        });
        jPanel5.add(btn_calculate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, -1, -1));

        cmb_PBP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_PBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 72, 84, -1));

        cmb_PBPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_PBPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 114, 84, -1));

        cmb_IAC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_IAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 84, -1));

        cmb_IB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_IB, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 84, -1));

        cmb_PE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_PE, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 84, -1));

        cmb_BS1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_BS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 84, -1));

        cmb_SE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_SE, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 615, 84, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(204, 0, 51));
        jLabel59.setText("Your GPA is:");
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 110, -1));

        lbl_gpa3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel5.add(lbl_gpa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 110, 30));

        jLabel60.setText("Introduction to Biochemistry");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        cmb_PD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_PD, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 156, 84, -1));
        jPanel5.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 543, 20));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setText("Nuclear Science");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel63.setText("Nuclear Technology in Sri Lanka");
        jPanel5.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        cmb_NT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_NT, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 84, -1));

        cmb_GSO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", " " }));
        jPanel5.add(cmb_GSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 84, -1));

        jLabel61.setText("Genome Structure and Organisation");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        mainPanel.add(jPanel5, "SySs");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton1.setText("Reset");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 800, -1, -1));

        jMenu1.setText("First Year");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("First Semester");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Second Semester");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Second Year");

        jMenuItem3.setText("First Semester");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Second Semester");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Third Year");

        jMenuItem5.setText("First Semester");
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Second Semester");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Fourth Year");

        jMenuItem7.setText("First Semester");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem8.setText("Second Semester");
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "SySs");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
                    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "FyFs");                           // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
                    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
                    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
                      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "FySs");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "SyFs");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_calculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculateMouseClicked
        Bio_FirstSemesterGPA b = new Bio_FirstSemesterGPA((cmb_GCB.getSelectedItem()).toString(),(cmb_GCBP.getSelectedItem()).toString(),(cmb_PR.getSelectedItem()).toString(),(cmb_PS.getSelectedItem()).toString(),(cmb_GPC.getSelectedItem()).toString(),(cmb_CC.getSelectedItem()).toString(),(cmb_PC.getSelectedItem()).toString(),(cmb_EB.getSelectedItem()).toString(),(cmb_ES.getSelectedItem()).toString(),(cmb_AM.getSelectedItem()).toString(),(cmb_CS.getSelectedItem()).toString());
        GPA = b.calculateFFGPA((cmb_GCB.getSelectedItem()).toString(),(cmb_GCBP.getSelectedItem()).toString(),(cmb_PR.getSelectedItem()).toString(),(cmb_PS.getSelectedItem()).toString(),(cmb_GPC.getSelectedItem()).toString(),(cmb_CC.getSelectedItem()).toString(),(cmb_PC.getSelectedItem()).toString(),(cmb_EB.getSelectedItem()).toString(),(cmb_ES.getSelectedItem()).toString(),(cmb_AM.getSelectedItem()).toString(),(cmb_CS.getSelectedItem()).toString());
        lbl_gpa.setText(String.format("%.5g%n",GPA));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calculateMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btn_calculate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculate1MouseClicked
          BioI_SecondSemester b = new BioI_SecondSemester((cmb_PML.getSelectedItem()).toString(),(cmb_PMLP.getSelectedItem()).toString(),(cmb_FS.getSelectedItem()).toString(),(cmb_OC.getSelectedItem()).toString(),(cmb_ICS.getSelectedItem()).toString(),(cmb_PCA.getSelectedItem()).toString(),(cmb_AL.getSelectedItem()).toString(),(cmb_AB.getSelectedItem()).toString(),(cmb_FP.getSelectedItem()).toString());          
          GPA = b.calculateFSGPA((cmb_PML.getSelectedItem()).toString(),(cmb_PMLP.getSelectedItem()).toString(),(cmb_FS.getSelectedItem()).toString(),(cmb_OC.getSelectedItem()).toString(),(cmb_ICS.getSelectedItem()).toString(),(cmb_PCA.getSelectedItem()).toString(),(cmb_AL.getSelectedItem()).toString(),(cmb_AB.getSelectedItem()).toString(),(cmb_FP.getSelectedItem()).toString());
          lbl_gpa1.setText(String.format("%.5g%n",GPA));  // TODO add your handling code here:
    }//GEN-LAST:event_btn_calculate1MouseClicked

    private void btn_calculate2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculate2MouseClicked
            BioII_FirstSemester b = new BioII_FirstSemester((cmb_MB.getSelectedItem()).toString(),(cmb_MBRD.getSelectedItem()).toString(),(cmb_BS.getSelectedItem()).toString(),(cmb_MMP.getSelectedItem()).toString(),(cmb_PCII.getSelectedItem()).toString(),(cmb_IPC.getSelectedItem()).toString(),(cmb_AF.getSelectedItem()).toString(),(cmb_EM.getSelectedItem()).toString(),(cmb_NS.getSelectedItem()).toString(),(cmb_IT.getSelectedItem()).toString());
            GPA = b.calculateSFGPA((cmb_MB.getSelectedItem()).toString(),(cmb_MBRD.getSelectedItem()).toString(),(cmb_BS.getSelectedItem()).toString(),(cmb_MMP.getSelectedItem()).toString(),(cmb_PCII.getSelectedItem()).toString(),(cmb_IPC.getSelectedItem()).toString(),(cmb_AF.getSelectedItem()).toString(),(cmb_EM.getSelectedItem()).toString(),(cmb_NS.getSelectedItem()).toString(),(cmb_IT.getSelectedItem()).toString());
            lbl_gpa2.setText(String.format("%.5g%n",GPA));          // TODO add your handling code here:
    }//GEN-LAST:event_btn_calculate2MouseClicked

    private void btn_calculate3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculate3MouseClicked
            BioII_SecondSemester b = new BioII_SecondSemester((cmb_PBP.getSelectedItem()).toString(),(cmb_PBPP.getSelectedItem()).toString(),(cmb_PD.getSelectedItem()).toString(),(cmb_IAC.getSelectedItem()).toString(),(cmb_IB.getSelectedItem()).toString(),(cmb_GSO.getSelectedItem()).toString(),(cmb_PE.getSelectedItem()).toString(),(cmb_BS1.getSelectedItem()).toString(),(cmb_NT.getSelectedItem()).toString(),(cmb_SE.getSelectedItem()).toString());
            GPA = b.calculateSSGPA((cmb_PBP.getSelectedItem()).toString(),(cmb_PBPP.getSelectedItem()).toString(),(cmb_PD.getSelectedItem()).toString(),(cmb_IAC.getSelectedItem()).toString(),(cmb_IB.getSelectedItem()).toString(),(cmb_GSO.getSelectedItem()).toString(),(cmb_PE.getSelectedItem()).toString(),(cmb_BS1.getSelectedItem()).toString(),(cmb_NT.getSelectedItem()).toString(),(cmb_SE.getSelectedItem()).toString());
            lbl_gpa3.setText(String.format("%.5g%n",GPA));        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calculate3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    cmb_AB.setSelectedItem("--");
    cmb_AF.setSelectedItem("--");
    cmb_AL.setSelectedItem("--");
    cmb_AM.setSelectedItem("--");
    cmb_BS.setSelectedItem("--");
    cmb_BS1.setSelectedItem("--");
    cmb_CC.setSelectedItem("--");
    cmb_CS.setSelectedItem("--");
    cmb_EB.setSelectedItem("--");
    cmb_EM.setSelectedItem("--");
    cmb_ES.setSelectedItem("--");
    cmb_FP.setSelectedItem("--");
    cmb_FS.setSelectedItem("--");
    cmb_GCB.setSelectedItem("--");
    cmb_GCBP.setSelectedItem("--");
    cmb_GPC.setSelectedItem("--");
    cmb_GSO.setSelectedItem("--");
    cmb_IAC.setSelectedItem("--");
    cmb_IB.setSelectedItem("--");
    cmb_ICS.setSelectedItem("--");
    cmb_IPC.setSelectedItem("--");
    cmb_IT.setSelectedItem("--");
    cmb_MB.setSelectedItem("--");
    cmb_MBRD.setSelectedItem("--");
    cmb_MMP.setSelectedItem("--");
    cmb_NS.setSelectedItem("--");
    cmb_NT.setSelectedItem("--");
    cmb_OC.setSelectedItem("--");
    cmb_PBP.setSelectedItem("--");
    cmb_PBPP.setSelectedItem("--");
    cmb_PC.setSelectedItem("--");
    cmb_PCA.setSelectedItem("--");
    cmb_PCII.setSelectedItem("--");
    cmb_PD.setSelectedItem("--");
    cmb_PE.setSelectedItem("--");
    cmb_PML.setSelectedItem("--");
    cmb_PMLP.setSelectedItem("--");
    cmb_PR.setSelectedItem("--");
    cmb_PS.setSelectedItem("--");
    cmb_SE.setSelectedItem("--");
    lbl_gpa.setText("");
    lbl_gpa1.setText("");
    lbl_gpa2.setText("");
    lbl_gpa3.setText("");// TODO add our handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Years.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Years.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Years.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Years.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Years().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_calculate1;
    private javax.swing.JButton btn_calculate2;
    private javax.swing.JButton btn_calculate3;
    private javax.swing.JComboBox<String> cmb_AB;
    private javax.swing.JComboBox<String> cmb_AF;
    private javax.swing.JComboBox<String> cmb_AL;
    private javax.swing.JComboBox<String> cmb_AM;
    private javax.swing.JComboBox<String> cmb_BS;
    private javax.swing.JComboBox<String> cmb_BS1;
    private javax.swing.JComboBox<String> cmb_CC;
    private javax.swing.JComboBox<String> cmb_CS;
    private javax.swing.JComboBox<String> cmb_EB;
    private javax.swing.JComboBox<String> cmb_EM;
    private javax.swing.JComboBox<String> cmb_ES;
    private javax.swing.JComboBox<String> cmb_FP;
    private javax.swing.JComboBox<String> cmb_FS;
    private javax.swing.JComboBox<String> cmb_GCB;
    private javax.swing.JComboBox<String> cmb_GCBP;
    private javax.swing.JComboBox<String> cmb_GPC;
    private javax.swing.JComboBox<String> cmb_GSO;
    private javax.swing.JComboBox<String> cmb_IAC;
    private javax.swing.JComboBox<String> cmb_IB;
    private javax.swing.JComboBox<String> cmb_ICS;
    private javax.swing.JComboBox<String> cmb_IPC;
    private javax.swing.JComboBox<String> cmb_IT;
    private javax.swing.JComboBox<String> cmb_MB;
    private javax.swing.JComboBox<String> cmb_MBRD;
    private javax.swing.JComboBox<String> cmb_MMP;
    private javax.swing.JComboBox<String> cmb_NS;
    private javax.swing.JComboBox<String> cmb_NT;
    private javax.swing.JComboBox<String> cmb_OC;
    private javax.swing.JComboBox<String> cmb_PBP;
    private javax.swing.JComboBox<String> cmb_PBPP;
    private javax.swing.JComboBox<String> cmb_PC;
    private javax.swing.JComboBox<String> cmb_PCA;
    private javax.swing.JComboBox<String> cmb_PCII;
    private javax.swing.JComboBox<String> cmb_PD;
    private javax.swing.JComboBox<String> cmb_PE;
    private javax.swing.JComboBox<String> cmb_PML;
    private javax.swing.JComboBox<String> cmb_PMLP;
    private javax.swing.JComboBox<String> cmb_PR;
    private javax.swing.JComboBox<String> cmb_PS;
    private javax.swing.JComboBox<String> cmb_SE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbl_gpa;
    private javax.swing.JLabel lbl_gpa1;
    private javax.swing.JLabel lbl_gpa2;
    private javax.swing.JLabel lbl_gpa3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
